### POST 관리자 로그인
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "idNumber": "9999999999",
  "password": "1234"
}

> {%
    client.test("Login successful", function () {
        client.assert(response.status === 200, "Login failed with status " + response.status);
        client.assert(response.body.accessToken, "No accessToken found in response");
    });
    client.global.set("auth_token", response.body.accessToken);
%}

### POST 시험 신청 기간 추가
POST {{host}}/api/exam-period
Content-Type:application/json
Authorization: Bearer {{auth_token}}

{
  "year": "2025",
  "semester": "2",
  "midStartDateTime": "2025-11-01T10:00:00",
  "midEndDateTime": "2025-11-01T10:00:00",
  "finalStartDateTime": "2025-11-01T10:00:00",
  "finalEndDateTime": "2025-11-01T10:00:00"
}

> {%
    client.test("Response status is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Check created data", function () {
        client.assert(response.body.year === "2025", "Field 'year' value mismatch.");
        client.assert(response.body.semester === "2", "Field 'semester' value mismatch.");
        client.assert(response.body.midStartDateTime === "2025-11-01T10:00:00", "Field 'midStartDateTime' value mismatch.");
        client.assert(response.body.midEndDateTime === "2025-11-01T10:00:00", "Field 'midEndDateTime' value mismatch.");
        client.assert(response.body.finalStartDateTime === "2025-11-01T10:00:00", "Field 'finalStartDateTime' value mismatch.");
        client.assert(response.body.finalEndDateTime === "2025-11-01T10:00:00", "Field 'finalEndDateTime' value mismatch.");
    })
    client.global.set("exam_period_id", response.body.examPeriodId)
%}

### GET 시험 신청 기간 조회
GET {{host}}/api/exam-period?year=2025&semester=2
Authorization: Bearer {{auth_token}}

> {%
    client.test("Response status is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Check retrieved data", function () {
        client.assert(response.body.year === "2025", "Field 'year' value mismatch.");
        client.assert(response.body.semester === "2", "Field 'semester' value mismatch.");
    })

%}