name: Spring Boot CI/CD with Docker

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '17'
      DOCKER_IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}/assignx-server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build Spring Boot Application
        run: ./gradlew bootJar -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_REPO }}:${{ github.run_number }}
            ${{ env.DOCKER_IMAGE_REPO }}:latest

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Logged into remote server: ${{ secrets.SSH_HOST }}"
            
            cd /home/${{ secrets.SSH_USERNAME }}/Workspace
            
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -af

            echo "Deployment completed"